import {test} from 'node:test';import assert from 'node:assert/strict';import {KEYS,createBackup,parseBackup,restoreBackup,rollbackRestore,MAX_BYTES} from '../lib/backup.mjs';
class Store {data=new Map(); getItem(k){return this.data.get(k)??null;}setItem(k,v){if(this.failKey===k){this.failKey=null;throw Error('Quota');}this.data.set(k,v);}removeItem(k){this.data.delete(k);}}
const data={profile:{name:'Student',selectedSubjects:['m1'],setupComplete:true,theme:'dark',streak:1,lastStudyDate:'2026-10-10'},progress:[{unitId:'m1-u1',status:'Mastered',pyqsCompleted:['2024']}],marks:{m1:{inSem:30,endSem:70,termWork:25}},tasks:[{id:'a',text:'Revise',completed:true,priority:'NORMAL',category:'EXAM',createdAt:'2026-10-10'}],resources:[{id:'r',type:'link',title:'Notes',author:'Me',downloads:'',subject:'m1',category:'Notes',url:'https://example.com'}],hiddenResourceIds:['system1']};
const seed=()=>{const s=new Store();for(const [f,k] of Object.entries(KEYS))s.setItem(k,JSON.stringify(data[f]));return s;};
test('all state round-trips to fresh storage; actual progress key',()=>{const b=createBackup(seed());const s=new Store();restoreBackup(s,parseBackup(JSON.stringify(b),data).data);assert.deepEqual(createBackup(s).data,data);assert.equal(s.getItem('sppu_user_progress'),null);});
test('invalid files never write',()=>{for(const mutate of [b=>b.metadata.version='9',b=>b.data.progress[0].status='Invented',b=>b.data.marks.m1.endSem=90,b=>delete b.data.tasks,b=>b.data.resources[0].url='javascript:alert(1)']){const s=seed(),before=[...s.data];const b=createBackup(s);mutate(b);assert.throws(()=>parseBackup(JSON.stringify(b),data));assert.deepEqual([...s.data],before);}assert.throws(()=>parseBackup('{',data));assert.throws(()=>parseBackup('x'.repeat(MAX_BYTES+1),data));});
test('quota failure restores prior fields and rollback',()=>{const s=seed(),before=[...s.data];s.failKey=KEYS.tasks;assert.throws(()=>restoreBackup(s,{...data,progress:[],tasks:[]}));assert.deepEqual([...s.data],before);});
test('rollback reverses a successful replacement',()=>{const s=seed();restoreBackup(s,{...data,progress:[],tasks:[]});rollbackRestore(s);assert.deepEqual(createBackup(s).data,data);});
test('legacy wrapped/raw formats keep omitted fields with warnings',()=>{const b={metadata:{type:'SPPU_PREPTRACKER_LOCAL_BACKUP',version:'3.1.0'},data:{...data}};delete b.data.hiddenResourceIds;const p=parseBackup(JSON.stringify(b),data);assert.deepEqual(p.data.hiddenResourceIds,data.hiddenResourceIds);assert.ok(p.warnings.length);const raw={profile:JSON.stringify(data.profile),progress:JSON.stringify(data.progress)};assert.deepEqual(parseBackup(JSON.stringify(raw),data).data,data);});
