import{test}from'node:test';import assert from'node:assert/strict';import{learningNodes,migrateLearning,recordAttempt,editReview,undoAttempt,learningSummary,reviewDay}from'../lib/learning.mjs';import{createBackup,parseBackup,restoreBackup,rollbackRestore,KEYS}from'../lib/backup.mjs';
const course={id:'se-c',source:'https://university.example/syllabus.pdf',units:[{id:'se-u1',title:'Methods',unit_number:1,sourceText:'Matrices; Vectors. Calculus',topics:['Matrices; Vectors. Calculus']}]};
const old={topics:{'se-u1:topic:1':{status:'done',confidence:'high',lastRevised:'2026-10-10'}},events:[{id:'old',topicId:'se-u1:topic:1',confidence:'high',kind:'revision',day:'2026-10-10',at:'2026-10-10T10:00:00Z'}],plan:[{id:'p',topicId:'se-u1:topic:1',courseId:'se-c',label:'Methods',reason:'Revision due',date:'2026-10-10',minutes:20,status:'planned'}]};
const args={topicId:'child',courseId:'se-c',unitId:'se-u1',goal:'Explain the method',answer:'My reasoning',paper:false,outcome:'hint',reference:{kind:'user',label:'My checked notes',text:'A user-provided comparison'},day:'2026-12-31',at:'2026-12-31T12:00:00Z',attemptId:'a'};
test('source nodes stable across unrelated insertion; duplicate spans distinct; no source rewriting',()=>{const n=learningNodes(course);assert.equal(n.length,3);assert.equal(n[0].text,'Matrices');assert.equal(n[0].aggregateId,'se-u1:topic:1');const changed=structuredClone(course);changed.units[0].sourceText='New material; '+course.units[0].sourceText;assert.equal(learningNodes(changed)[1].id,n[0].id);changed.units[0].sourceText='Same; Same';assert.notEqual(...learningNodes(changed).map(x=>x.id));assert.equal(course.units[0].topics[0],'Matrices; Vectors. Calculus');});
test('FE keeps existing topic IDs',()=>{const c={...course,units:[{id:'m1-u1',topics:['Rolle','Taylor']}]};assert.deepEqual(learningNodes(c).map(n=>n.id),['m1-u1:topic:1','m1-u1:topic:2']);});
test('migration idempotent and preserves aggregate events/plan; no inherited child evidence',()=>{const s=migrateLearning(old);assert.deepEqual(s.topics,old.topics);assert.deepEqual(s.events,old.events);assert.deepEqual(s.plan,old.plan);assert.equal(migrateLearning(s),s);assert.deepEqual(learningSummary(learningNodes(course),s),{total:3,covered:0,attempted:0,due:0,attempts:0});});
test('attempt, reference and outcome are required; syllabus reference rejected',()=>{for(const change of [{answer:'',paper:false},{reference:{kind:'syllabus',label:'Syllabus',text:'Topic'}},{reference:null},{outcome:'mastered'},{review:'2026-02-30'}])assert.throws(()=>recordAttempt(old,{...args,...change}));assert.equal(recordAttempt(old,{...args,answer:'',paper:true}).attempts.length,1);});
test('outcome schedules transparent 1/3/7 calendar days, coverage and legacy logs unchanged',()=>{const s=recordAttempt(old,args);assert.equal(s.topics.child.nextReview,'2027-01-03');assert.equal(s.topics.child.status,undefined);assert.deepEqual(s.events,old.events);assert.equal(s.attempts[0].reference.kind,'user');assert.equal(reviewDay('2026-12-31','solo'),'2027-01-07');});
test('review edit, null review and summary separate coverage/attempted/due',()=>{let s=recordAttempt(old,args);s=editReview(s,'child',null);assert.equal(learningSummary([{id:'child'}],s,'2027-02-01').due,0);s=editReview(s,'child','2027-01-02');assert.equal(learningSummary([{id:'child'}],s,'2027-02-01').due,1);assert.equal(learningSummary([{id:'child'}],s).covered,0);});
test('undo restores previous recall, preserves later coverage, rejects out-of-order undo',()=>{let s=recordAttempt(old,args);s.topics.child.status='done';s=undoAttempt(s,'a');assert.deepEqual(s.topics.child,{status:'done'});assert.deepEqual(s.events,old.events);s=recordAttempt(old,args);s=recordAttempt(s,{...args,attemptId:'b',outcome:'solo'});assert.throws(()=>undoAttempt(s,'a'));s=undoAttempt(s,'b');assert.equal(s.topics.child.outcome,'hint');s=undoAttempt(s,'a');assert.equal(s.topics.child,undefined);});
class Store{data=new Map();getItem(k){return this.data.get(k)??null;}setItem(k,v){if(this.fail===k){this.fail=null;throw Error('Quota')}this.data.set(k,v)}removeItem(k){this.data.delete(k)}}
test('v6 full loop export/restore/rollback and old v5 compatible; malformed new data rejected',()=>{const store=new Store();store.setItem(KEYS.study,JSON.stringify(recordAttempt(old,args)));const b=createBackup(store);assert.equal(b.metadata.version,'6.0.0');const fresh=new Store();const parsed=parseBackup(JSON.stringify(b),b.data);restoreBackup(fresh,parsed.data);assert.deepEqual(createBackup(fresh).data,b.data);restoreBackup(fresh,{...b.data,study:old});rollbackRestore(fresh);assert.deepEqual(createBackup(fresh).data,b.data);const v5={...b,metadata:{...b.metadata,version:'5.0.0'},data:{...b.data,study:old}};assert.deepEqual(parseBackup(JSON.stringify(v5),b.data).data.study,old);const bad=structuredClone(b);bad.data.study.attempts[0].reference.url='javascript:bad';assert.throws(()=>parseBackup(JSON.stringify(bad),b.data));});
test('new-state restore quota failure retains old complete snapshot',()=>{const store=new Store();const oldBackup=createBackup(store);store.fail=KEYS.study;assert.throws(()=>restoreBackup(store,{...oldBackup.data,study:recordAttempt(old,args)}));assert.deepEqual(createBackup(store).data,oldBackup.data);});
