// Live source pages checked 2026-10-10. Supplemental, not SPPU papers/assessment keys.
export const REVIEWED_MATERIALS=[
 {id:'openstax-mvt',title:'Rolle and Mean Value Theorem: explanations, worked examples & exercises',publisher:'OpenStax / Calculus Volume 1',url:'https://openstax.org/books/calculus-volume-1/pages/4-4-the-mean-value-theorem',courseNames:/mathematics/i,topics:/rolle|mean value/i,kind:'Worked examples + exercises',fit:'Direct topic overlap. Not an SPPU question paper or official answer key.',checked:'2026-10-10'},
 {id:'openstax-kirchhoff',title:'Kirchhoff rules: junctions, loops and worked circuit analysis',publisher:'OpenStax / University Physics Volume 2',url:'https://openstax.org/books/university-physics-volume-2/pages/10-3-kirchhoffs-rules',courseNames:/electrical|circuit|network/i,topics:/kirchhoff|kvl|kcl/i,kind:'Worked circuit analysis',fit:'Direct KCL/KVL overlap. Check your own circuit and conventions; not a whole-course match.',checked:'2026-10-10'},
 {id:'openstax-laser',title:'Lasers: population inversion, stimulated emission and optical feedback',publisher:'OpenStax / University Physics Volume 3',url:'https://openstax.org/books/university-physics-volume-3/pages/8-6-lasers',courseNames:/physics/i,topics:/laser|stimulat/i,kind:'Mechanism explanation',fit:'Supports laser principles. Does not establish full CO2 construction or SPPU answer coverage.',checked:'2026-10-10'},
 {id:'mit-algorithms',title:'Algorithms: problem sets paired with solutions',publisher:'MIT OpenCourseWare / 6.006 Spring 2020',url:'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/pages/assignments/',courseNames:/data structures|algorithm/i,topics:/algorithm|complexity|sorting|search|tree|graph|hash/i,kind:'Course-level practice collection',fit:'Supplemental algorithm/data-structure practice. Browse for a matching problem; individual problem-to-syllabus mapping not completed. Python materials, not a C-language substitute.',checked:'2026-10-10'}
];
export function matchedMaterials(course,text){return REVIEWED_MATERIALS.filter(r=>r.courseNames.test(course.name)&&r.topics.test(text));}
export function resourceMatches(course,r){return r.subject===course.id||r.subject===course.code||course.code.startsWith(r.subject+'-')||(r.subject==='GLOBAL'&&course.year==='FE');}
export function classifyResource(r){return /syllabus|handbook|credit framework/i.test(r.title)?'Syllabus / rules, not study answers':r.isSystem?'Legacy course reference; topic fit not reviewed':'Your saved material; not independently reviewed';}
