// Preparation approaches are product guidance, not official syllabus claims.
export function subjectMethod(course){
 const name=course.name.toLowerCase();
 if(/mathemat|calculus|probability|statistics/.test(name))return{key:'math',label:'Reason on paper',verb:'Solve & justify',color:'#d7d9c5',steps:['State the givens and the method you chose.','Work line by line. Explain the step where the method applies.','Check the result against a worked solution and test the assumptions.'],prompt:'Choose one problem from your notes. Write the givens, solve it and explain why the method applies.',check:'Compare the method, intermediate steps and final result. A matching final number alone is not enough.'};
 if(/programming|data structure|algorithm|computer|database|operating|software|intelligence|data science/.test(name))return{key:'code',label:'Trace the machine',verb:'Trace, build & test',color:'#d1ccc3',steps:['Choose a concrete input, case or query.','Trace the state changes, or write the smallest working implementation.','Check an edge case and explain what fails or why it works.'],prompt:'Choose a concrete example from your materials. Trace its states, write an implementation or explain the design decision.',check:'Compare behavior on a normal case and an edge case. Include your reasoning, not only remembered definitions.'};
 if(/graphics|design|drawing/.test(name))return{key:'draw',label:'Make the construction',verb:'Sketch & construct',color:'#dfc3b5',steps:['Read the givens and choose the view or construction.','Draw the stages on paper, preserving dimensions and conventions.','Compare each stage with a worked drawing, not only the finished shape.'],prompt:'Choose one drawing task. Record the givens, construction stages and the part you need to check.',check:'Use your own paper drawing and a worked reference. This app cannot judge geometry or inspect the drawing.'};
 if(/electr|circuit|network|signal/.test(name))return{key:'circuit',label:'Follow the circuit',verb:'Model & calculate',color:'#d9d0bb',steps:['Draw the circuit and mark known values, polarity and assumptions.','Choose a law or model; keep units through every step.','Check the limiting case and compare with a worked solution.'],prompt:'Choose a circuit or device problem. Sketch it on paper, choose the model and work through its behavior.',check:'Check the diagram, sign convention, units and result against your reference.'};
 if(/physics|mechanics|chemistry|thermo|fluid|material/.test(name))return{key:'science',label:'Explain the mechanism',verb:'Model, derive & check',color:'#cbd5ce',steps:['Sketch the physical system or mechanism and state the assumptions.','Explain the cause or derive the result, keeping units visible.','Compare the reasoning and test a limiting case against your material.'],prompt:'Choose a phenomenon, derivation or numerical problem. Explain the mechanism or work through the model on paper.',check:'Check the assumptions, mechanism, units and derivation. The source heading is not a solution.'};
 return{key:'explain',label:'Make an argument',verb:'Explain & apply',color:'#d8c8b8',steps:['Choose one question or case from your materials.','Make the argument from memory, with a concrete example.','Compare against a trusted reference and identify what is missing.'],prompt:'Choose a question from your material. Answer it with an example and explain your reasoning.',check:'Compare the explanation and example with your reference, not only the vocabulary.'};
}
